FROM mcr.microsoft.com/playwright:v1.57.0-noble

WORKDIR /app

RUN apt-get update && apt-get install -y unzip \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm
ENV PNPM_CONFIG_LOGLEVEL=info
ENV PATH="/root/.pnpm/bin:$PATH"

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml /app/
COPY frontend/package.json /app/frontend/


RUN pnpm install --filter frontend

COPY ./frontend /app/frontend

ARG VITE_API_URL
